### ISSUE TITLE
Crash with fresco v1.8.1

### ISSUE THREAD

**Issue by skydoves** [qhutch/ElevationImageView#1]
It makes crash with fresco version 1.8.1.

![2018-03-19 3 38 00](https://user-images.githubusercontent.com/24237865/37581708-12e879ac-2b8d-11e8-95fb-2425a347d41d.png)

and fresco can not load .so file, it makes crash.

**Comment by qhutch** [comment]
Hi,
Did you add the renderscript part in your build.gralde ?
If so, can you try without my library but with the renderscript lines to see if the problem comes from the renderscript version

**Comment by skydoves** [comment]
I solved the issue by adding below options on build.gradle

```groovy
packagingOptions {
        exclude '/lib/mips64/**'
        exclude '/lib/arm64-v8a/**'
        exclude '/lib/x86_64/**'
    }
```

If not, it will crash with fresco over v1.8.1 regardless renderScript. 
Thank you!
