### ISSUE TITLE
Drawing over the actionbar

### ISSUE THREAD

**Issue by dovahkiin98** [qhutch/ElevationImageView#10]
In my layout the actionbar is transparent. When I set the clipBounds to false, the shadow draws over the actionbar in scrolling.
![screenshot_1529309272](https://user-images.githubusercontent.com/8161112/41524927-dc4faf62-72e7-11e8-8a93-3ac703b6866e.png)

**Comment by qhutch** [comment]
Which version of the library are you using ?
I use two different ways of drawing outside the view padding in v1.7.3 and v1.7 can you try using both of those versions and tell me if one works for you ?
I plan to merge the two versions and make one available with a boolean parameter

**Comment by dovahkiin98** [comment]
I used the code on the library cause I wanted to try and tweak some things.
Now I tried v1.7.3 no issue.
Tho would you kindly help me do the same for TextView? I'm stuck on trying to convert the text into a bitmap.

```kotlin
private val drawable: Drawable
        get() = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888).apply {
            val canvas = Canvas(this)
            canvas.drawText("Hello World", 0f, 0f, paint)
        }.toDrawable(resources)
```

**Comment by qhutch** [comment]
This lines should work. How do you get width and height for the bitmap ?

**Comment by dovahkiin98** [comment]
the getWidth and getHeight of the view

**Comment by qhutch** [comment]
You can try to get a bitmap from a view with the getDrawingCache() method, but it means the view should have been drawn at least once before

**Comment by dovahkiin98** [comment]
mind sharing the code for the new way of drawing outside the padding?

**Comment by qhutch** [comment]
I don't have the computer I coded it on with me, but I'll push the code as soon as I'll have it

**Comment by qhutch** [comment]
You can now use v2.0 with attribute "forceClip" set to true instead of v1.7.3, the code has been pushed on the repo
