### ISSUE TITLE
Android P Issue:  java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by 0megaD** [qhutch/ElevationImageView#11]
As subject title states the following error occurs:
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
When attempting to draw the ElevationImageView on Android P.

This is due to the following line:
canvas.clipRect(rect, Region.Op.REPLACE)

See the following issue on stackoverflow for a suggested replacement:
https://stackoverflow.com/questions/50231950/what-is-the-best-alternative-to-canvas-cliprect-with-region-op-replace

**Comment by jlurena** [comment]
I'm addressing this issue with PR https://github.com/qhutch/ElevationImageView/pull/12 
@qhutch please review
